function onServerStart()
	outputDebugString("#####################################")
	outputDebugString("##    MTA:DayZ Epoch - 0.4.528b    ##")
	outputDebugString("##          	                    ##")
	outputDebugString("##          	 Launched           ##")
	outputDebugString("#####################################")
	setTimer ( function()
		outputDebugString("#####################################")
		outputDebugString("##             Features            ##")
		outputDebugString("#####################################")
		outputDebugString("##         - New mechanics         ##")
		outputDebugString("##         - Optimization          ##")
		outputDebugString("##         - New weapons           ##")
		outputDebugString("##         - Trade zone            ##")
		outputDebugString("##         - Money                 ##")
		outputDebugString("##          	                    ##")
		outputDebugString("##           And more...           ##")
		outputDebugString("#####################################")
	end, 5000, 1 )
	setTimer ( function()
		outputDebugString("Ready to welcome players !")
	end, 8000, 1 )
end
addEventHandler("onResourceStart", getResourceRootElement(getThisResource()), onServerStart)