g_Root = getRootElement()


countryNames = {
AD="Andorra",
AE="Arabian",
AF="Afghanistan",
AG="Antigua Bardura",
AI="Anguilla",
AL="Albania",
AM="Armenia",
AN="Netherlands Antilles",
AO="Angola",
AP="Asia",
AR="Argentina",
AS="American Samoa",
AT="Austria",
AU="Australia",
AW="Aruba",
AZ="Azerbaijan",
BA="Bosnia Herzrgowina",
BB="Barbados",
BD="Bangladesh",
BE="Belgium",
BF="Burkina Faso",
BG="Bulgaria",
BH="Bahrain",
BI="Burundi",
BJ="Benin",
BM="Bermuda",
BN="Brunei Darussalam",
BO="Bolivia",
BR="BR",
BS="Bahamas",
BT="Bhutan",
BW="Botswana",
BY="Belarus",
BZ="Belize",
CA="Canada",
CD="Congo The Democratic",
CF="Centra African Republic",
CH="Switzerland",
CI="Cote Divoire",
CK="Cook Isladinds",
CL="Chile",
CM="Cameroon",
CN="China",
CO="Colombia",
CR="Costa Rica",
CS="Serbia and Montenegro",
CU="Cuba",
CY="CY",
CZ="Czech Republic",
DE="Alemania",
DJ="Djibouti",
DK="Denmark",
DO="Dominican Republic",
DZ="Algeria",
EC="Ecuador",
EE="Estonia",
EG="Egipto",
ER="Eritrea",
ES="España",
ET="Ethiopia",
EU="Europa",
FI="Finland",
FJ="Fiji",
FM="Microdencia",
FO="Faroe Islands",
FR="France",
GA="Gabon",
GB="United Kingdom",
GD="Grenada",
GE="Géorgie",
GF="French Guinia",
GH="Ghana",
GI="GibraItar",
GL="Greenland",
GM="Gambia",
GR="Greece",
GT="Guatelama",
GU="Guam",
GW="Guinea",
GY="GUYANA",
HK="HONG KONG",
HN="HONDURAS",
HR="Croacia",
HT="Haiti",
HU="Hungary",
ID="Indonecia",
IE="Ireland",
IL="Isral",
IN="India",
IO="India Ocean",
IQ="Iraq",
IR="Iran",
IS="Iceland",
IT="Italia",
JM="Jamaica",
JO="Jorlan",
JP="Japon",
KE="Kenya",
KG="Kyrgyzstan",
KH="Cambodia",
KI="Kiribati",
KN="Saint Kitts And Nevis",
KR="Korea",
KW="Kuwait",
KY="Cayman Islands",
KZ="Kazakhstan",
LA="Democratic Republic",
LB="Lebaton",
LC="Santa Lucia",
LI="Liechtenstein",
LK="Sri Lanka",
LR="Liberia",
LS="Lesotho",
LT="LithuaniaI",
LU="Luxembourg",
LV="LATVIA",
LY="Libyan Arab",
MA="Morocco",
MC="Monaco",
MD="Moldoca Republic",
MG="MadagascarA",
MK="MK",
ML="Malia",
MM="Myanmar",
MN="Mongolia",
MO="MACAU",
MP="MP",
MR="Mauritania",
MT="Malta",
MU="Mauritius",
MV="Maldives",
MW="Malawi",
MX="Mexcio",
MY="Malaysia",
MZ="Mozambique",
NA="NAMIBIA",
NC="NEW CALEDONIA",
NE="Nigger",
NF="Norfolk Island",
NG="Nigeria",
NI="Nicaragua",
NL="Netherlands",
NO="Norway",
NP="Nepal",
NR="Nauru",
NU="Niuse",
NZ="New Zealand",
OM="Oman",
PA="Parama",
PE="Peru",
PF="French Polynesia",
PG="Papua New Guinea",
PH="Philippines",
PK="Pakistan",
PL="Polonia",
PR="Puerto Rico",
PS="Palestian",
PT="PORTUGAL",
PW="Palau",
PY="Paraguay",
QA="Qatar",
RO="Romania",
RU="Russian",
RW="Rwanda",
SA="Saudi Arabian",
SB="Solomon Islands",
SC="Seychelles",
SD="Sudan",
SE="Sweden",
SG="Singapore",
SI="Slovenia",
SK="Slovak Republic",
SL="Sierra Leone",
SM="San Marino",
SN="Senegal",
SR="Suriname",
SV="El Salvador",
SY="Syrian Arab Republic",
SZ="Swaziland",
TG="Togo",
TH="Thailand",
TJ="Tajikistan",
TM="Turkmenistan",
TN="Tunisia",
TO="Tonga",
TR="Turkey",
TT="Trinidad Tobago",
TV="Tuvalu",
TW="Taiwan Province China",
TZ="Tanzania",
UA="Ukranie",
UG="Uganda",
US="United States",
UY="Uruguat",
UZ="Uzbekistan",
VA="Vatican City",
VE="Venezuela",
VG="Virgin Islands (British)",
VI="Virgin Islands (U.S.)",
VN="Vietnam",
VU="Vauanuatu",
WS="Samoa",
YE="Yemen",
YU="Formally Yugoslavia",
ZA="Sudrafica",
ZM="Zambia",
ZW="Zimbabwe",
ZZ="Reserved"
}


addEventHandler('onPlayerJoin',g_Root,
function ()
    local country = exports['admin']:getPlayerCountry(source)
    setElementData(source,'Country',country)
    outputChatBox('#ff0000*[MTA:DayZ] #ffffff' .. getPlayerName(source) .. '#ffffff a rejoint le serveur #ff0000[' .. countryNames[tostring(country)] .. ']', getRootElement(), 2, 255, 2, true)
    end
)

addEventHandler('onPlayerChangeNick', g_Root,
    function(oldNick, newNick)
        outputChatBox('#ff0000*[MTA:DayZ] #ffffff' .. oldNick .. '#ffffff a changer son pseudo par ' .. newNick, getRootElement(), 3, 180, 255, true)
    end
)
 
addEventHandler('onPlayerQuit', g_Root,
    function(reason)
        outputChatBox('#ff0000*[MTA:DayZ] #ffffff' .. getPlayerName(source) .. '#ffffff a quitté le serveur #ff0000[' .. reason .. ']', getRootElement(), 255, 0, 0, true)
    end
)